name: Publish to PyPi

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.7.1
      - name: Publish SD-WAN Lab Deployment Tool
        run: |
          poetry config pypi-token.pypi ${{ secrets.SDWAN_LAB_DEPLOYMENT_TOOL_PYPI_TOKEN }}
          poetry publish --build